version: '3.8'
services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - ./mysql/config:/etc/mysql/mysql.conf.d
      - ./mysql/db:/opt/db
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
  nacos:
    restart: always
    image: nacos/nacos-server:v2.2.1
    # 容器名称
    container_name: nacos
    # 端口映射
    ports:
      - "8848:8848"
      - "9848:9848"
    # 容器权限
    privileged: true
    # 参数设置。本地开发测试使用，调低内存占用
    environment:
      JVM_XMS: 128m
      JVM_XMX: 128m
      JVM_MS: 64m
      JVM_MMS: 64m
      MODE: standalone
      NACOS_REPLICAS: 1
      PREFER_HOST_MODE: hostname
    volumes:
      - /opt/docker_nacos/logs:/home/nacos/logs
      - /opt/docker_nacos/plugins:/home/nacos/plugins
      - /opt/docker_nacos/data:/home/nacos/data
      - ./nacos/config/application.properties:/home/nacos/conf/application.properties
    depends_on:
      - mysql
  redis:
    restart: always
    image: redis:7.2.0
    # 容器名称
    container_name: redis
    # 端口映射
    ports:
      - "6379:6379"