server:
  port: 12002 # user

spring:
  jackson:
    serialization:
      # date序列化给前端时，转成时间戳格式
      write-date-keys-as-timestamps: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo_2022_09_04?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      idle-timeout: 30000
      maximum-pool-size: 50
      connection-timeout: 60000
  liquibase:
    enabled: true
  data:
    redis:
      host: 127.0.0.1
      port: 6379

mybatis-plus:
  mapper-locations:
    - "classpath:mapper/user/*.xml"
  configuration:
    ### 开启打印sql配置
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl